### ISSUE TITLE
Добавить гиперссылки в блок "В этом месяце я хочу"

### ISSUE THREAD

**Issue by Ira306** [thallkeer/diary-app#20]
1) Переименовать блок в "Я хочу"
2) Сделать возможность добавления гиперссылки во всех трёх столбцах "Прочитать", "Посетить", "Посмотреть" аналогично гиперссылкам в блоке "Покупки"

**Comment by thallkeer** [comment]
Добавил ссылки во все списки в блоке. А также сделал ссылки в блоке "Идеи".
Нужно еще переименовать названия блоков.
