### ISSUE TITLE
Переносы второй страницы

### ISSUE THREAD

**Issue by Ira306** [thallkeer/diary-app#23]
1) Настроить вторую страницу так, чтобы блоки "Покупки", "Я хочу" и "Идеи" не нудно было перетаскивать из месяца в месяц, чтобы они были статичны. Меняется только блок "Цели на этот месяц"
2) Переименовать блок "Цели на этот месяц" в "Трекеры привычек"
3) Если решим оставить переносы, то переноситься на следующий месяц должны только блоки, выбранные пользователем и только те записи в блоках, которые не отмечены голубым кружком как выполненные

**Comment by thallkeer** [comment]
1. Решили, что это будет делаться через настройки пользователя. Можно будет настроить один раз, что автоматом переносятся выбранные списки каждый месяц.
3. Решили отменить
